from vsdnemul.dataplane import Dataplane
from vsdnemul.lib.log import get_logger
from vsdnemul.link import LinkType
from vsdnemul.models.link.linkpair import LinkPair
from vsdnemul.models.node.host.host import Host
from vsdnemul.models.node.switch.whitebox import Whitebox
from vsdnemul.models.node.controller.onos import Onos
from vsdnemul.cli import Cli


if __name__ == '__main__':
    logger = get_logger(__name__)

    # Define Dataplane

    dp = Dataplane()

    # Adding Controller

    ctl = dp.addNode(Onos(name="ctl1"))
    mgnt = "tcp:{ip}:6653".format(ip=ctl.getIpController())

    # Adding nodes to dataplane
    # Create Switch Nodes
    wth = 256

    for i in range(1, wth):
    	locals()["sw"+str(i)] = dp.addNode(Whitebox("sw"+str(i)))

    # Create Host Nodes

    h1 = dp.addNode(Host(name="h1", ip="10.0.0.1", mask="24"))
    h2 = dp.addNode(Host(name="h2", ip="10.0.0.2", mask="24"))

    # Adding links to dataplane
    l1 = dp.addLink(LinkPair(name="l1", node_source=sw1, node_target=sw2, type=LinkType.DIRECT))
    l2 = dp.addLink(LinkPair(name="l2", node_source=sw1, node_target=sw129, type=LinkType.DIRECT))
    l3 = dp.addLink(LinkPair(name="l3", node_source=sw2, node_target=sw3, type=LinkType.DIRECT))
    l4 = dp.addLink(LinkPair(name="l4", node_source=sw2, node_target=sw66, type=LinkType.DIRECT))
    l5 = dp.addLink(LinkPair(name="l5", node_source=sw3, node_target=sw4, type=LinkType.DIRECT))
    l6 = dp.addLink(LinkPair(name="l6", node_source=sw3, node_target=sw35, type=LinkType.DIRECT))
    l7 = dp.addLink(LinkPair(name="l7", node_source=sw4, node_target=sw5, type=LinkType.DIRECT))
    l8 = dp.addLink(LinkPair(name="l8", node_source=sw4, node_target=sw20, type=LinkType.DIRECT))
    l9 = dp.addLink(LinkPair(name="l9", node_source=sw5, node_target=sw6, type=LinkType.DIRECT))
    l10 = dp.addLink(LinkPair(name="l10", node_source=sw5, node_target=sw13, type=LinkType.DIRECT))
    l11 = dp.addLink(LinkPair(name="l11", node_source=sw6, node_target=sw7, type=LinkType.DIRECT))
    l12 = dp.addLink(LinkPair(name="l12", node_source=sw6, node_target=sw10, type=LinkType.DIRECT))
    l13 = dp.addLink(LinkPair(name="l13", node_source=sw7, node_target=sw8, type=LinkType.DIRECT))
    l14 = dp.addLink(LinkPair(name="l14", node_source=sw7, node_target=sw9, type=LinkType.DIRECT))
    l15 = dp.addLink(LinkPair(name="l15", node_source=sw10, node_target=sw11, type=LinkType.DIRECT))
    l16 = dp.addLink(LinkPair(name="l16", node_source=sw10, node_target=sw12, type=LinkType.DIRECT))
    l17 = dp.addLink(LinkPair(name="l17", node_source=sw13, node_target=sw14, type=LinkType.DIRECT))
    l18 = dp.addLink(LinkPair(name="l18", node_source=sw13, node_target=sw17, type=LinkType.DIRECT))
    l19 = dp.addLink(LinkPair(name="l19", node_source=sw14, node_target=sw15, type=LinkType.DIRECT))
    l20 = dp.addLink(LinkPair(name="l20", node_source=sw14, node_target=sw16, type=LinkType.DIRECT))
    l21 = dp.addLink(LinkPair(name="l21", node_source=sw17, node_target=sw18, type=LinkType.DIRECT))
    l22 = dp.addLink(LinkPair(name="l22", node_source=sw17, node_target=sw19, type=LinkType.DIRECT))
    l23 = dp.addLink(LinkPair(name="l23", node_source=sw20, node_target=sw21, type=LinkType.DIRECT))
    l24 = dp.addLink(LinkPair(name="l24", node_source=sw20, node_target=sw28, type=LinkType.DIRECT))
    l25 = dp.addLink(LinkPair(name="l25", node_source=sw21, node_target=sw22, type=LinkType.DIRECT))
    l26 = dp.addLink(LinkPair(name="l26", node_source=sw21, node_target=sw25, type=LinkType.DIRECT))
    l27 = dp.addLink(LinkPair(name="l27", node_source=sw22, node_target=sw23, type=LinkType.DIRECT))
    l28 = dp.addLink(LinkPair(name="l28", node_source=sw22, node_target=sw24, type=LinkType.DIRECT))
    l29 = dp.addLink(LinkPair(name="l29", node_source=sw25, node_target=sw26, type=LinkType.DIRECT))
    l30 = dp.addLink(LinkPair(name="l30", node_source=sw25, node_target=sw27, type=LinkType.DIRECT))
    l31 = dp.addLink(LinkPair(name="l31", node_source=sw28, node_target=sw29, type=LinkType.DIRECT))
    l32 = dp.addLink(LinkPair(name="l32", node_source=sw28, node_target=sw32, type=LinkType.DIRECT))
    l33 = dp.addLink(LinkPair(name="l33", node_source=sw29, node_target=sw30, type=LinkType.DIRECT))
    l34 = dp.addLink(LinkPair(name="l34", node_source=sw29, node_target=sw31, type=LinkType.DIRECT))
    l35 = dp.addLink(LinkPair(name="l35", node_source=sw32, node_target=sw33, type=LinkType.DIRECT))
    l36 = dp.addLink(LinkPair(name="l36", node_source=sw32, node_target=sw34, type=LinkType.DIRECT))
    l37 = dp.addLink(LinkPair(name="l37", node_source=sw35, node_target=sw36, type=LinkType.DIRECT))
    l38 = dp.addLink(LinkPair(name="l38", node_source=sw35, node_target=sw51, type=LinkType.DIRECT))
    l39 = dp.addLink(LinkPair(name="l39", node_source=sw36, node_target=sw37, type=LinkType.DIRECT))
    l40 = dp.addLink(LinkPair(name="l40", node_source=sw36, node_target=sw44, type=LinkType.DIRECT))
    l41 = dp.addLink(LinkPair(name="l41", node_source=sw37, node_target=sw38, type=LinkType.DIRECT))
    l42 = dp.addLink(LinkPair(name="l42", node_source=sw37, node_target=sw41, type=LinkType.DIRECT))
    l43 = dp.addLink(LinkPair(name="l43", node_source=sw38, node_target=sw39, type=LinkType.DIRECT))
    l44 = dp.addLink(LinkPair(name="l44", node_source=sw38, node_target=sw40, type=LinkType.DIRECT))
    l45 = dp.addLink(LinkPair(name="l45", node_source=sw41, node_target=sw42, type=LinkType.DIRECT))
    l46 = dp.addLink(LinkPair(name="l46", node_source=sw41, node_target=sw43, type=LinkType.DIRECT))
    l47 = dp.addLink(LinkPair(name="l47", node_source=sw44, node_target=sw45, type=LinkType.DIRECT))
    l48 = dp.addLink(LinkPair(name="l48", node_source=sw44, node_target=sw48, type=LinkType.DIRECT))
    l49 = dp.addLink(LinkPair(name="l49", node_source=sw45, node_target=sw46, type=LinkType.DIRECT))
    l50 = dp.addLink(LinkPair(name="l50", node_source=sw45, node_target=sw47, type=LinkType.DIRECT))
    l51 = dp.addLink(LinkPair(name="l51", node_source=sw48, node_target=sw49, type=LinkType.DIRECT))
    l52 = dp.addLink(LinkPair(name="l52", node_source=sw48, node_target=sw50, type=LinkType.DIRECT))
    l53 = dp.addLink(LinkPair(name="l53", node_source=sw51, node_target=sw52, type=LinkType.DIRECT))
    l54 = dp.addLink(LinkPair(name="l54", node_source=sw51, node_target=sw59, type=LinkType.DIRECT))
    l55 = dp.addLink(LinkPair(name="l55", node_source=sw52, node_target=sw53, type=LinkType.DIRECT))
    l56 = dp.addLink(LinkPair(name="l56", node_source=sw52, node_target=sw56, type=LinkType.DIRECT))
    l57 = dp.addLink(LinkPair(name="l57", node_source=sw53, node_target=sw54, type=LinkType.DIRECT))
    l58 = dp.addLink(LinkPair(name="l58", node_source=sw53, node_target=sw55, type=LinkType.DIRECT))
    l59 = dp.addLink(LinkPair(name="l59", node_source=sw56, node_target=sw57, type=LinkType.DIRECT))
    l60 = dp.addLink(LinkPair(name="l60", node_source=sw56, node_target=sw58, type=LinkType.DIRECT))
    l61 = dp.addLink(LinkPair(name="l61", node_source=sw59, node_target=sw60, type=LinkType.DIRECT))
    l62 = dp.addLink(LinkPair(name="l62", node_source=sw59, node_target=sw63, type=LinkType.DIRECT))
    l63 = dp.addLink(LinkPair(name="l63", node_source=sw60, node_target=sw61, type=LinkType.DIRECT))
    l64 = dp.addLink(LinkPair(name="l64", node_source=sw60, node_target=sw62, type=LinkType.DIRECT))
    l65 = dp.addLink(LinkPair(name="l65", node_source=sw63, node_target=sw64, type=LinkType.DIRECT))
    l66 = dp.addLink(LinkPair(name="l66", node_source=sw63, node_target=sw65, type=LinkType.DIRECT))
    l67 = dp.addLink(LinkPair(name="l67", node_source=sw66, node_target=sw67, type=LinkType.DIRECT))
    l68 = dp.addLink(LinkPair(name="l68", node_source=sw66, node_target=sw98, type=LinkType.DIRECT))
    l69 = dp.addLink(LinkPair(name="l69", node_source=sw67, node_target=sw68, type=LinkType.DIRECT))
    l70 = dp.addLink(LinkPair(name="l70", node_source=sw67, node_target=sw83, type=LinkType.DIRECT))
    l71 = dp.addLink(LinkPair(name="l71", node_source=sw68, node_target=sw69, type=LinkType.DIRECT))
    l72 = dp.addLink(LinkPair(name="l72", node_source=sw68, node_target=sw76, type=LinkType.DIRECT))
    l73 = dp.addLink(LinkPair(name="l73", node_source=sw69, node_target=sw70, type=LinkType.DIRECT))
    l74 = dp.addLink(LinkPair(name="l74", node_source=sw69, node_target=sw73, type=LinkType.DIRECT))
    l75 = dp.addLink(LinkPair(name="l75", node_source=sw70, node_target=sw71, type=LinkType.DIRECT))
    l76 = dp.addLink(LinkPair(name="l76", node_source=sw70, node_target=sw72, type=LinkType.DIRECT))
    l77 = dp.addLink(LinkPair(name="l77", node_source=sw73, node_target=sw74, type=LinkType.DIRECT))
    l78 = dp.addLink(LinkPair(name="l78", node_source=sw73, node_target=sw75, type=LinkType.DIRECT))
    l79 = dp.addLink(LinkPair(name="l79", node_source=sw76, node_target=sw77, type=LinkType.DIRECT))
    l80 = dp.addLink(LinkPair(name="l80", node_source=sw76, node_target=sw80, type=LinkType.DIRECT))
    l81 = dp.addLink(LinkPair(name="l81", node_source=sw77, node_target=sw78, type=LinkType.DIRECT))
    l82 = dp.addLink(LinkPair(name="l82", node_source=sw77, node_target=sw79, type=LinkType.DIRECT))
    l83 = dp.addLink(LinkPair(name="l83", node_source=sw80, node_target=sw81, type=LinkType.DIRECT))
    l84 = dp.addLink(LinkPair(name="l84", node_source=sw80, node_target=sw82, type=LinkType.DIRECT))
    l85 = dp.addLink(LinkPair(name="l85", node_source=sw83, node_target=sw84, type=LinkType.DIRECT))
    l86 = dp.addLink(LinkPair(name="l86", node_source=sw83, node_target=sw91, type=LinkType.DIRECT))
    l87 = dp.addLink(LinkPair(name="l87", node_source=sw84, node_target=sw85, type=LinkType.DIRECT))
    l88 = dp.addLink(LinkPair(name="l88", node_source=sw84, node_target=sw88, type=LinkType.DIRECT))
    l89 = dp.addLink(LinkPair(name="l89", node_source=sw85, node_target=sw86, type=LinkType.DIRECT))
    l90 = dp.addLink(LinkPair(name="l90", node_source=sw85, node_target=sw87, type=LinkType.DIRECT))
    l91 = dp.addLink(LinkPair(name="l91", node_source=sw88, node_target=sw89, type=LinkType.DIRECT))
    l92 = dp.addLink(LinkPair(name="l92", node_source=sw88, node_target=sw90, type=LinkType.DIRECT))
    l93 = dp.addLink(LinkPair(name="l93", node_source=sw91, node_target=sw92, type=LinkType.DIRECT))
    l94 = dp.addLink(LinkPair(name="l94", node_source=sw91, node_target=sw95, type=LinkType.DIRECT))
    l95 = dp.addLink(LinkPair(name="l95", node_source=sw92, node_target=sw93, type=LinkType.DIRECT))
    l96 = dp.addLink(LinkPair(name="l96", node_source=sw92, node_target=sw94, type=LinkType.DIRECT))
    l97 = dp.addLink(LinkPair(name="l97", node_source=sw95, node_target=sw96, type=LinkType.DIRECT))
    l98 = dp.addLink(LinkPair(name="l98", node_source=sw95, node_target=sw97, type=LinkType.DIRECT))
    l99 = dp.addLink(LinkPair(name="l99", node_source=sw98, node_target=sw99, type=LinkType.DIRECT))
    l100 = dp.addLink(LinkPair(name="l100", node_source=sw98, node_target=sw114, type=LinkType.DIRECT))
    l101 = dp.addLink(LinkPair(name="l101", node_source=sw99, node_target=sw100, type=LinkType.DIRECT))
    l102 = dp.addLink(LinkPair(name="l102", node_source=sw99, node_target=sw107, type=LinkType.DIRECT))
    l103 = dp.addLink(LinkPair(name="l103", node_source=sw100, node_target=sw101, type=LinkType.DIRECT))
    l104 = dp.addLink(LinkPair(name="l104", node_source=sw100, node_target=sw104, type=LinkType.DIRECT))
    l105 = dp.addLink(LinkPair(name="l105", node_source=sw101, node_target=sw102, type=LinkType.DIRECT))
    l106 = dp.addLink(LinkPair(name="l106", node_source=sw101, node_target=sw103, type=LinkType.DIRECT))
    l107 = dp.addLink(LinkPair(name="l107", node_source=sw104, node_target=sw105, type=LinkType.DIRECT))
    l108 = dp.addLink(LinkPair(name="l108", node_source=sw104, node_target=sw106, type=LinkType.DIRECT))
    l109 = dp.addLink(LinkPair(name="l109", node_source=sw107, node_target=sw108, type=LinkType.DIRECT))
    l110 = dp.addLink(LinkPair(name="l110", node_source=sw107, node_target=sw111, type=LinkType.DIRECT))
    l111 = dp.addLink(LinkPair(name="l111", node_source=sw108, node_target=sw109, type=LinkType.DIRECT))
    l112 = dp.addLink(LinkPair(name="l112", node_source=sw108, node_target=sw110, type=LinkType.DIRECT))
    l113 = dp.addLink(LinkPair(name="l113", node_source=sw111, node_target=sw112, type=LinkType.DIRECT))
    l114 = dp.addLink(LinkPair(name="l114", node_source=sw111, node_target=sw113, type=LinkType.DIRECT))
    l115 = dp.addLink(LinkPair(name="l115", node_source=sw114, node_target=sw115, type=LinkType.DIRECT))
    l116 = dp.addLink(LinkPair(name="l116", node_source=sw114, node_target=sw122, type=LinkType.DIRECT))
    l117 = dp.addLink(LinkPair(name="l117", node_source=sw115, node_target=sw116, type=LinkType.DIRECT))
    l118 = dp.addLink(LinkPair(name="l118", node_source=sw115, node_target=sw119, type=LinkType.DIRECT))
    l119 = dp.addLink(LinkPair(name="l119", node_source=sw116, node_target=sw117, type=LinkType.DIRECT))
    l120 = dp.addLink(LinkPair(name="l120", node_source=sw116, node_target=sw118, type=LinkType.DIRECT))
    l121 = dp.addLink(LinkPair(name="l121", node_source=sw119, node_target=sw120, type=LinkType.DIRECT))
    l122 = dp.addLink(LinkPair(name="l122", node_source=sw119, node_target=sw121, type=LinkType.DIRECT))
    l123 = dp.addLink(LinkPair(name="l123", node_source=sw122, node_target=sw123, type=LinkType.DIRECT))
    l124 = dp.addLink(LinkPair(name="l124", node_source=sw122, node_target=sw126, type=LinkType.DIRECT))
    l125 = dp.addLink(LinkPair(name="l125", node_source=sw123, node_target=sw124, type=LinkType.DIRECT))
    l126 = dp.addLink(LinkPair(name="l126", node_source=sw123, node_target=sw125, type=LinkType.DIRECT))
    l127 = dp.addLink(LinkPair(name="l127", node_source=sw126, node_target=sw127, type=LinkType.DIRECT))
    l128 = dp.addLink(LinkPair(name="l128", node_source=sw126, node_target=sw128, type=LinkType.DIRECT))
    l129 = dp.addLink(LinkPair(name="l129", node_source=sw129, node_target=sw130, type=LinkType.DIRECT))
    l130 = dp.addLink(LinkPair(name="l130", node_source=sw129, node_target=sw193, type=LinkType.DIRECT))
    l131 = dp.addLink(LinkPair(name="l131", node_source=sw130, node_target=sw131, type=LinkType.DIRECT))
    l132 = dp.addLink(LinkPair(name="l132", node_source=sw130, node_target=sw162, type=LinkType.DIRECT))
    l133 = dp.addLink(LinkPair(name="l133", node_source=sw131, node_target=sw132, type=LinkType.DIRECT))
    l134 = dp.addLink(LinkPair(name="l134", node_source=sw131, node_target=sw147, type=LinkType.DIRECT))
    l135 = dp.addLink(LinkPair(name="l135", node_source=sw132, node_target=sw133, type=LinkType.DIRECT))
    l136 = dp.addLink(LinkPair(name="l136", node_source=sw132, node_target=sw140, type=LinkType.DIRECT))
    l137 = dp.addLink(LinkPair(name="l137", node_source=sw133, node_target=sw134, type=LinkType.DIRECT))
    l138 = dp.addLink(LinkPair(name="l138", node_source=sw133, node_target=sw137, type=LinkType.DIRECT))
    l139 = dp.addLink(LinkPair(name="l139", node_source=sw134, node_target=sw135, type=LinkType.DIRECT))
    l140 = dp.addLink(LinkPair(name="l140", node_source=sw134, node_target=sw136, type=LinkType.DIRECT))
    l141 = dp.addLink(LinkPair(name="l141", node_source=sw137, node_target=sw138, type=LinkType.DIRECT))
    l142 = dp.addLink(LinkPair(name="l142", node_source=sw137, node_target=sw139, type=LinkType.DIRECT))
    l143 = dp.addLink(LinkPair(name="l143", node_source=sw140, node_target=sw141, type=LinkType.DIRECT))
    l144 = dp.addLink(LinkPair(name="l144", node_source=sw140, node_target=sw144, type=LinkType.DIRECT))
    l145 = dp.addLink(LinkPair(name="l145", node_source=sw141, node_target=sw142, type=LinkType.DIRECT))
    l146 = dp.addLink(LinkPair(name="l146", node_source=sw141, node_target=sw143, type=LinkType.DIRECT))
    l147 = dp.addLink(LinkPair(name="l147", node_source=sw144, node_target=sw145, type=LinkType.DIRECT))
    l148 = dp.addLink(LinkPair(name="l148", node_source=sw144, node_target=sw146, type=LinkType.DIRECT))
    l149 = dp.addLink(LinkPair(name="l149", node_source=sw147, node_target=sw148, type=LinkType.DIRECT))
    l150 = dp.addLink(LinkPair(name="l150", node_source=sw147, node_target=sw155, type=LinkType.DIRECT))
    l151 = dp.addLink(LinkPair(name="l151", node_source=sw148, node_target=sw149, type=LinkType.DIRECT))
    l152 = dp.addLink(LinkPair(name="l152", node_source=sw148, node_target=sw152, type=LinkType.DIRECT))
    l153 = dp.addLink(LinkPair(name="l153", node_source=sw149, node_target=sw150, type=LinkType.DIRECT))
    l154 = dp.addLink(LinkPair(name="l154", node_source=sw149, node_target=sw151, type=LinkType.DIRECT))
    l155 = dp.addLink(LinkPair(name="l155", node_source=sw152, node_target=sw153, type=LinkType.DIRECT))
    l156 = dp.addLink(LinkPair(name="l156", node_source=sw152, node_target=sw154, type=LinkType.DIRECT))
    l157 = dp.addLink(LinkPair(name="l157", node_source=sw155, node_target=sw156, type=LinkType.DIRECT))
    l158 = dp.addLink(LinkPair(name="l158", node_source=sw155, node_target=sw159, type=LinkType.DIRECT))
    l159 = dp.addLink(LinkPair(name="l159", node_source=sw156, node_target=sw157, type=LinkType.DIRECT))
    l160 = dp.addLink(LinkPair(name="l160", node_source=sw156, node_target=sw158, type=LinkType.DIRECT))
    l161 = dp.addLink(LinkPair(name="l161", node_source=sw159, node_target=sw160, type=LinkType.DIRECT))
    l162 = dp.addLink(LinkPair(name="l162", node_source=sw159, node_target=sw161, type=LinkType.DIRECT))
    l163 = dp.addLink(LinkPair(name="l163", node_source=sw162, node_target=sw163, type=LinkType.DIRECT))
    l164 = dp.addLink(LinkPair(name="l164", node_source=sw162, node_target=sw178, type=LinkType.DIRECT))
    l165 = dp.addLink(LinkPair(name="l165", node_source=sw163, node_target=sw164, type=LinkType.DIRECT))
    l166 = dp.addLink(LinkPair(name="l166", node_source=sw163, node_target=sw171, type=LinkType.DIRECT))
    l167 = dp.addLink(LinkPair(name="l167", node_source=sw164, node_target=sw165, type=LinkType.DIRECT))
    l168 = dp.addLink(LinkPair(name="l168", node_source=sw164, node_target=sw168, type=LinkType.DIRECT))
    l169 = dp.addLink(LinkPair(name="l169", node_source=sw165, node_target=sw166, type=LinkType.DIRECT))
    l170 = dp.addLink(LinkPair(name="l170", node_source=sw165, node_target=sw167, type=LinkType.DIRECT))
    l171 = dp.addLink(LinkPair(name="l171", node_source=sw168, node_target=sw169, type=LinkType.DIRECT))
    l172 = dp.addLink(LinkPair(name="l172", node_source=sw168, node_target=sw170, type=LinkType.DIRECT))
    l173 = dp.addLink(LinkPair(name="l173", node_source=sw171, node_target=sw172, type=LinkType.DIRECT))
    l174 = dp.addLink(LinkPair(name="l174", node_source=sw171, node_target=sw175, type=LinkType.DIRECT))
    l175 = dp.addLink(LinkPair(name="l175", node_source=sw172, node_target=sw173, type=LinkType.DIRECT))
    l176 = dp.addLink(LinkPair(name="l176", node_source=sw172, node_target=sw174, type=LinkType.DIRECT))
    l177 = dp.addLink(LinkPair(name="l177", node_source=sw175, node_target=sw176, type=LinkType.DIRECT))
    l178 = dp.addLink(LinkPair(name="l178", node_source=sw175, node_target=sw177, type=LinkType.DIRECT))
    l179 = dp.addLink(LinkPair(name="l179", node_source=sw178, node_target=sw179, type=LinkType.DIRECT))
    l180 = dp.addLink(LinkPair(name="l180", node_source=sw178, node_target=sw186, type=LinkType.DIRECT))
    l181 = dp.addLink(LinkPair(name="l181", node_source=sw179, node_target=sw180, type=LinkType.DIRECT))
    l182 = dp.addLink(LinkPair(name="l182", node_source=sw179, node_target=sw183, type=LinkType.DIRECT))
    l183 = dp.addLink(LinkPair(name="l183", node_source=sw180, node_target=sw181, type=LinkType.DIRECT))
    l184 = dp.addLink(LinkPair(name="l184", node_source=sw180, node_target=sw182, type=LinkType.DIRECT))
    l185 = dp.addLink(LinkPair(name="l185", node_source=sw183, node_target=sw184, type=LinkType.DIRECT))
    l186 = dp.addLink(LinkPair(name="l186", node_source=sw183, node_target=sw185, type=LinkType.DIRECT))
    l187 = dp.addLink(LinkPair(name="l187", node_source=sw186, node_target=sw187, type=LinkType.DIRECT))
    l188 = dp.addLink(LinkPair(name="l188", node_source=sw186, node_target=sw190, type=LinkType.DIRECT))
    l189 = dp.addLink(LinkPair(name="l189", node_source=sw187, node_target=sw188, type=LinkType.DIRECT))
    l190 = dp.addLink(LinkPair(name="l190", node_source=sw187, node_target=sw189, type=LinkType.DIRECT))
    l191 = dp.addLink(LinkPair(name="l191", node_source=sw190, node_target=sw191, type=LinkType.DIRECT))
    l192 = dp.addLink(LinkPair(name="l192", node_source=sw190, node_target=sw192, type=LinkType.DIRECT))
    l193 = dp.addLink(LinkPair(name="l193", node_source=sw193, node_target=sw194, type=LinkType.DIRECT))
    l194 = dp.addLink(LinkPair(name="l194", node_source=sw193, node_target=sw225, type=LinkType.DIRECT))
    l195 = dp.addLink(LinkPair(name="l195", node_source=sw194, node_target=sw195, type=LinkType.DIRECT))
    l196 = dp.addLink(LinkPair(name="l196", node_source=sw194, node_target=sw210, type=LinkType.DIRECT))
    l197 = dp.addLink(LinkPair(name="l197", node_source=sw195, node_target=sw196, type=LinkType.DIRECT))
    l198 = dp.addLink(LinkPair(name="l198", node_source=sw195, node_target=sw203, type=LinkType.DIRECT))
    l199 = dp.addLink(LinkPair(name="l199", node_source=sw196, node_target=sw197, type=LinkType.DIRECT))
    l200 = dp.addLink(LinkPair(name="l200", node_source=sw196, node_target=sw200, type=LinkType.DIRECT))
    l201 = dp.addLink(LinkPair(name="l201", node_source=sw197, node_target=sw198, type=LinkType.DIRECT))
    l202 = dp.addLink(LinkPair(name="l202", node_source=sw197, node_target=sw199, type=LinkType.DIRECT))
    l203 = dp.addLink(LinkPair(name="l203", node_source=sw200, node_target=sw201, type=LinkType.DIRECT))
    l204 = dp.addLink(LinkPair(name="l204", node_source=sw200, node_target=sw202, type=LinkType.DIRECT))
    l205 = dp.addLink(LinkPair(name="l205", node_source=sw203, node_target=sw204, type=LinkType.DIRECT))
    l206 = dp.addLink(LinkPair(name="l206", node_source=sw203, node_target=sw207, type=LinkType.DIRECT))
    l207 = dp.addLink(LinkPair(name="l207", node_source=sw204, node_target=sw205, type=LinkType.DIRECT))
    l208 = dp.addLink(LinkPair(name="l208", node_source=sw204, node_target=sw206, type=LinkType.DIRECT))
    l209 = dp.addLink(LinkPair(name="l209", node_source=sw207, node_target=sw208, type=LinkType.DIRECT))
    l210 = dp.addLink(LinkPair(name="l210", node_source=sw207, node_target=sw209, type=LinkType.DIRECT))
    l211 = dp.addLink(LinkPair(name="l211", node_source=sw210, node_target=sw211, type=LinkType.DIRECT))
    l212 = dp.addLink(LinkPair(name="l212", node_source=sw210, node_target=sw218, type=LinkType.DIRECT))
    l213 = dp.addLink(LinkPair(name="l213", node_source=sw211, node_target=sw212, type=LinkType.DIRECT))
    l214 = dp.addLink(LinkPair(name="l214", node_source=sw211, node_target=sw215, type=LinkType.DIRECT))
    l215 = dp.addLink(LinkPair(name="l215", node_source=sw212, node_target=sw213, type=LinkType.DIRECT))
    l216 = dp.addLink(LinkPair(name="l216", node_source=sw212, node_target=sw214, type=LinkType.DIRECT))
    l217 = dp.addLink(LinkPair(name="l217", node_source=sw215, node_target=sw216, type=LinkType.DIRECT))
    l218 = dp.addLink(LinkPair(name="l218", node_source=sw215, node_target=sw217, type=LinkType.DIRECT))
    l219 = dp.addLink(LinkPair(name="l219", node_source=sw218, node_target=sw219, type=LinkType.DIRECT))
    l220 = dp.addLink(LinkPair(name="l220", node_source=sw218, node_target=sw222, type=LinkType.DIRECT))
    l221 = dp.addLink(LinkPair(name="l221", node_source=sw219, node_target=sw220, type=LinkType.DIRECT))
    l222 = dp.addLink(LinkPair(name="l222", node_source=sw219, node_target=sw221, type=LinkType.DIRECT))
    l223 = dp.addLink(LinkPair(name="l223", node_source=sw222, node_target=sw223, type=LinkType.DIRECT))
    l224 = dp.addLink(LinkPair(name="l224", node_source=sw222, node_target=sw224, type=LinkType.DIRECT))
    l225 = dp.addLink(LinkPair(name="l225", node_source=sw225, node_target=sw226, type=LinkType.DIRECT))
    l226 = dp.addLink(LinkPair(name="l226", node_source=sw225, node_target=sw241, type=LinkType.DIRECT))
    l227 = dp.addLink(LinkPair(name="l227", node_source=sw226, node_target=sw227, type=LinkType.DIRECT))
    l228 = dp.addLink(LinkPair(name="l228", node_source=sw226, node_target=sw234, type=LinkType.DIRECT))
    l229 = dp.addLink(LinkPair(name="l229", node_source=sw227, node_target=sw228, type=LinkType.DIRECT))
    l230 = dp.addLink(LinkPair(name="l230", node_source=sw227, node_target=sw231, type=LinkType.DIRECT))
    l231 = dp.addLink(LinkPair(name="l231", node_source=sw228, node_target=sw229, type=LinkType.DIRECT))
    l232 = dp.addLink(LinkPair(name="l232", node_source=sw228, node_target=sw230, type=LinkType.DIRECT))
    l233 = dp.addLink(LinkPair(name="l233", node_source=sw231, node_target=sw232, type=LinkType.DIRECT))
    l234 = dp.addLink(LinkPair(name="l234", node_source=sw231, node_target=sw233, type=LinkType.DIRECT))
    l235 = dp.addLink(LinkPair(name="l235", node_source=sw234, node_target=sw235, type=LinkType.DIRECT))
    l236 = dp.addLink(LinkPair(name="l236", node_source=sw234, node_target=sw238, type=LinkType.DIRECT))
    l237 = dp.addLink(LinkPair(name="l237", node_source=sw235, node_target=sw236, type=LinkType.DIRECT))
    l238 = dp.addLink(LinkPair(name="l238", node_source=sw235, node_target=sw237, type=LinkType.DIRECT))
    l239 = dp.addLink(LinkPair(name="l239", node_source=sw238, node_target=sw239, type=LinkType.DIRECT))
    l240 = dp.addLink(LinkPair(name="l240", node_source=sw238, node_target=sw240, type=LinkType.DIRECT))
    l241 = dp.addLink(LinkPair(name="l241", node_source=sw241, node_target=sw242, type=LinkType.DIRECT))
    l242 = dp.addLink(LinkPair(name="l242", node_source=sw241, node_target=sw249, type=LinkType.DIRECT))
    l243 = dp.addLink(LinkPair(name="l243", node_source=sw242, node_target=sw243, type=LinkType.DIRECT))
    l244 = dp.addLink(LinkPair(name="l244", node_source=sw242, node_target=sw246, type=LinkType.DIRECT))
    l245 = dp.addLink(LinkPair(name="l245", node_source=sw243, node_target=sw244, type=LinkType.DIRECT))
    l246 = dp.addLink(LinkPair(name="l246", node_source=sw243, node_target=sw245, type=LinkType.DIRECT))
    l247 = dp.addLink(LinkPair(name="l247", node_source=sw246, node_target=sw247, type=LinkType.DIRECT))
    l248 = dp.addLink(LinkPair(name="l248", node_source=sw246, node_target=sw248, type=LinkType.DIRECT))
    l249 = dp.addLink(LinkPair(name="l249", node_source=sw249, node_target=sw250, type=LinkType.DIRECT))
    l250 = dp.addLink(LinkPair(name="l250", node_source=sw249, node_target=sw253, type=LinkType.DIRECT))
    l251 = dp.addLink(LinkPair(name="l251", node_source=sw250, node_target=sw251, type=LinkType.DIRECT))
    l252 = dp.addLink(LinkPair(name="l252", node_source=sw250, node_target=sw252, type=LinkType.DIRECT))
    l253 = dp.addLink(LinkPair(name="l253", node_source=sw253, node_target=sw254, type=LinkType.DIRECT))
    l254 = dp.addLink(LinkPair(name="l254", node_source=sw253, node_target=sw255, type=LinkType.DIRECT))

    #connecting switches to Controller
    for i in range (1, wth):
    	locals()["sw"+str(i)].setController(target=mgnt, bridge="br_oper0")

    cli = Cli(dp)
    cli.cmdloop()

    dp.stop()



