from vsdnemul.dataplane import Dataplane
from vsdnemul.lib.log import get_logger
from vsdnemul.link import LinkType
from vsdnemul.models.link.linkpair import LinkPair
from vsdnemul.models.node.host.host import Host
from vsdnemul.models.node.switch.whitebox import Whitebox
from vsdnemul.models.node.controller.onos import Onos
from vsdnemul.cli import Cli


if __name__ == '__main__':
    logger = get_logger(__name__)

    # Define Dataplane

    dp = Dataplane()

     # Adding Controller
    ctl = dp.addNode(Onos(name="ctl1"))
    mgnt = "tcp:{ip}:6653".format(ip=ctl.getIpController())

    # Adding nodes to dataplane
    # Create Switch Nodes

    sw1 = dp.addNode(Whitebox("sw1"))
    sw72 = dp.addNode(Whitebox("sw72"))
    sw2 = dp.addNode(Whitebox("sw2"))
    sw3 = dp.addNode(Whitebox("sw3"))
    sw4 = dp.addNode(Whitebox("sw4"))
    sw5 = dp.addNode(Whitebox("sw5"))
    sw6 = dp.addNode(Whitebox("sw6"))
    sw7 = dp.addNode(Whitebox("sw7"))
    sw8 = dp.addNode(Whitebox("sw8"))
    sw9 = dp.addNode(Whitebox("sw9"))
    sw10 = dp.addNode(Whitebox("sw10"))
    sw11 = dp.addNode(Whitebox("sw11"))
    sw12 = dp.addNode(Whitebox("sw12"))
    sw13 = dp.addNode(Whitebox("sw13"))
    sw14 = dp.addNode(Whitebox("sw14"))
    sw15 = dp.addNode(Whitebox("sw15"))
    sw16 = dp.addNode(Whitebox("sw16"))
    sw17 = dp.addNode(Whitebox("sw17"))
    sw18 = dp.addNode(Whitebox("sw18"))
    sw19 = dp.addNode(Whitebox("sw19"))
    sw20 = dp.addNode(Whitebox("sw20"))
    sw21 = dp.addNode(Whitebox("sw21"))
    sw22 = dp.addNode(Whitebox("sw22"))
    sw23 = dp.addNode(Whitebox("sw23"))
    sw24 = dp.addNode(Whitebox("sw24"))
    sw25 = dp.addNode(Whitebox("sw25"))
    sw26 = dp.addNode(Whitebox("sw26"))
    sw27 = dp.addNode(Whitebox("sw27"))
    sw28 = dp.addNode(Whitebox("sw28"))
    sw29 = dp.addNode(Whitebox("sw29"))
    sw30 = dp.addNode(Whitebox("sw30"))
    sw31 = dp.addNode(Whitebox("sw31"))
    sw32 = dp.addNode(Whitebox("sw32"))
    sw33 = dp.addNode(Whitebox("sw33"))
    sw34 = dp.addNode(Whitebox("sw34"))
    sw35 = dp.addNode(Whitebox("sw35"))
    sw36 = dp.addNode(Whitebox("sw36"))
    sw37 = dp.addNode(Whitebox("sw37"))
    sw38 = dp.addNode(Whitebox("sw38"))
    sw39 = dp.addNode(Whitebox("sw39"))
    sw40 = dp.addNode(Whitebox("sw40"))
    sw41 = dp.addNode(Whitebox("sw41"))
    sw42 = dp.addNode(Whitebox("sw42"))
    sw43 = dp.addNode(Whitebox("sw43"))
    sw44 = dp.addNode(Whitebox("sw44"))
    sw45 = dp.addNode(Whitebox("sw45"))
    sw46 = dp.addNode(Whitebox("sw46"))
    sw47 = dp.addNode(Whitebox("sw47"))
    sw48 = dp.addNode(Whitebox("sw48"))
    sw49 = dp.addNode(Whitebox("sw49"))
    sw50 = dp.addNode(Whitebox("sw50"))
    sw51 = dp.addNode(Whitebox("sw51"))
    sw52 = dp.addNode(Whitebox("sw52"))
    sw53 = dp.addNode(Whitebox("sw53"))
    sw54 = dp.addNode(Whitebox("sw54"))
    sw55 = dp.addNode(Whitebox("sw55"))
    sw56 = dp.addNode(Whitebox("sw56"))
    sw57 = dp.addNode(Whitebox("sw57"))
    sw58 = dp.addNode(Whitebox("sw58"))
    sw59 = dp.addNode(Whitebox("sw59"))
    sw60 = dp.addNode(Whitebox("sw60"))
    sw61 = dp.addNode(Whitebox("sw61"))
    sw62 = dp.addNode(Whitebox("sw62"))
    sw63 = dp.addNode(Whitebox("sw63"))
    sw64 = dp.addNode(Whitebox("sw64"))
    sw65 = dp.addNode(Whitebox("sw65"))
    sw66 = dp.addNode(Whitebox("sw66"))
    sw67 = dp.addNode(Whitebox("sw67"))
    sw68 = dp.addNode(Whitebox("sw68"))
    sw69 = dp.addNode(Whitebox("sw69"))
    sw70 = dp.addNode(Whitebox("sw70"))
    sw71 = dp.addNode(Whitebox("sw71"))
    sw72 = dp.addNode(Whitebox("sw72"))
    sw73 = dp.addNode(Whitebox("sw73"))
    #sw74 = dp.addNode(Whitebox("sw74"))
    #sw75 = dp.addNode(Whitebox("sw75"))
    #sw76 = dp.addNode(Whitebox("sw76"))
    #sw77 = dp.addNode(Whitebox("sw77"))
    #sw78 = dp.addNode(Whitebox("sw78"))
    #sw79 = dp.addNode(Whitebox("sw79"))
    #sw80 = dp.addNode(Whitebox("sw80"))
    #sw81 = dp.addNode(Whitebox("sw81"))
    #sw82 = dp.addNode(Whitebox("sw82"))
    #sw83 = dp.addNode(Whitebox("sw83"))
    #sw84 = dp.addNode(Whitebox("sw84"))
    #sw85 = dp.addNode(Whitebox("sw85"))
    #sw86 = dp.addNode(Whitebox("sw86"))
    #sw87 = dp.addNode(Whitebox("sw87"))
    #sw88 = dp.addNode(Whitebox("sw88"))
    #sw89 = dp.addNode(Whitebox("sw89"))
    #sw90 = dp.addNode(Whitebox("sw90"))
    #sw91 = dp.addNode(Whitebox("sw91"))
    #sw92 = dp.addNode(Whitebox("sw92"))
    #sw93 = dp.addNode(Whitebox("sw93"))
    #sw94 = dp.addNode(Whitebox("sw94"))
    #sw95 = dp.addNode(Whitebox("sw95"))
    #sw96 = dp.addNode(Whitebox("sw96"))
    #sw97 = dp.addNode(Whitebox("sw97"))
    #sw98 = dp.addNode(Whitebox("sw98"))
    #sw99 = dp.addNode(Whitebox("sw99"))
    #sw100 = dp.addNode(Whitebox("sw100"))
    #sw101= dp.addNode(Whitebox("sw101"))
    #sw102 = dp.addNode(Whitebox("sw102"))
    #sw103 = dp.addNode(Whitebox("sw103"))
    #sw104 = dp.addNode(Whitebox("sw104"))
    #sw105 = dp.addNode(Whitebox("sw105"))
    #sw106 = dp.addNode(Whitebox("sw106"))
    #sw107 = dp.addNode(Whitebox("sw107"))
    #sw108 = dp.addNode(Whitebox("sw108"))
    #sw109 = dp.addNode(Whitebox("sw109"))
    #sw110 = dp.addNode(Whitebox("sw110"))
    #sw111 = dp.addNode(Whitebox("sw111"))
    #sw112 = dp.addNode(Whitebox("sw112"))
    #sw113 = dp.addNode(Whitebox("sw113"))
    #sw114 = dp.addNode(Whitebox("sw114"))
    #sw115 = dp.addNode(Whitebox("sw115"))
    #sw116 = dp.addNode(Whitebox("sw116"))
    #sw117 = dp.addNode(Whitebox("sw117"))
    #sw118 = dp.addNode(Whitebox("sw118"))
    #sw119 = dp.addNode(Whitebox("sw119"))
    #sw120 = dp.addNode(Whitebox("sw120"))
    #sw121 = dp.addNode(Whitebox("sw121"))
    #sw122 = dp.addNode(Whitebox("sw122"))
    #sw123 = dp.addNode(Whitebox("sw123"))
    #sw124 = dp.addNode(Whitebox("sw124"))
    #sw125 = dp.addNode(Whitebox("sw125"))
    #sw126 = dp.addNode(Whitebox("sw126"))
    #sw127 = dp.addNode(Whitebox("sw127"))


    # Create Host Nodes

    h1 = dp.addNode(Host(name="h1", ip="10.0.0.1", mask="24"))
    h2 = dp.addNode(Host(name="h2", ip="10.0.0.2", mask="24"))

    # Adding links to dataplane

    l1 = dp.addLink(LinkPair(name="l1", node_source=sw1, node_target=sw2, type=LinkType.DIRECT))
    l2 = dp.addLink(LinkPair(name="l2", node_source=sw1, node_target=sw65, type=LinkType.DIRECT))
    l3 = dp.addLink(LinkPair(name="l3", node_source=sw2, node_target=sw3, type=LinkType.DIRECT))
    l4 = dp.addLink(LinkPair(name="l4", node_source=sw2, node_target=sw34, type=LinkType.DIRECT))
    l5 = dp.addLink(LinkPair(name="l5", node_source=sw3, node_target=sw4, type=LinkType.DIRECT))
    
    l6 = dp.addLink(LinkPair(name="l6", node_source=sw3, node_target=sw19, type=LinkType.DIRECT))
    l7 = dp.addLink(LinkPair(name="l7", node_source=sw4, node_target=sw5, type=LinkType.DIRECT))
    l8 = dp.addLink(LinkPair(name="l8", node_source=sw4, node_target=sw12, type=LinkType.DIRECT))
    
    l9 = dp.addLink(LinkPair(name="l9", node_source=sw5, node_target=sw6, type=LinkType.DIRECT))
    l10 = dp.addLink(LinkPair(name="l10", node_source=sw5, node_target=sw9, type=LinkType.DIRECT))
    l11 = dp.addLink(LinkPair(name="l11", node_source=sw6, node_target=sw7, type=LinkType.DIRECT))
    l12 = dp.addLink(LinkPair(name="l12", node_source=sw6, node_target=sw8, type=LinkType.DIRECT))
    l13 = dp.addLink(LinkPair(name="l13", node_source=sw9, node_target=sw10, type=LinkType.DIRECT))
    l14 = dp.addLink(LinkPair(name="l14", node_source=sw9, node_target=sw11, type=LinkType.DIRECT))
    l15 = dp.addLink(LinkPair(name="l15", node_source=sw12, node_target=sw13, type=LinkType.DIRECT))

    l16 = dp.addLink(LinkPair(name="l16", node_source=sw12, node_target=sw16, type=LinkType.DIRECT))
    l17 = dp.addLink(LinkPair(name="l17", node_source=sw13, node_target=sw14, type=LinkType.DIRECT))
    l18 = dp.addLink(LinkPair(name="l18", node_source=sw13, node_target=sw15, type=LinkType.DIRECT))
    l19 = dp.addLink(LinkPair(name="l19", node_source=sw16, node_target=sw17, type=LinkType.DIRECT))
    l20 = dp.addLink(LinkPair(name="l20", node_source=sw16, node_target=sw18, type=LinkType.DIRECT))
    l21 = dp.addLink(LinkPair(name="l21", node_source=sw19, node_target=sw20, type=LinkType.DIRECT))
    l22 = dp.addLink(LinkPair(name="l22", node_source=sw19, node_target=sw27, type=LinkType.DIRECT))
    l23 = dp.addLink(LinkPair(name="l23", node_source=sw20, node_target=sw21, type=LinkType.DIRECT))

    l24 = dp.addLink(LinkPair(name="l24", node_source=sw20, node_target=sw24, type=LinkType.DIRECT))
    l25 = dp.addLink(LinkPair(name="l25", node_source=sw21, node_target=sw22, type=LinkType.DIRECT))
    l26 = dp.addLink(LinkPair(name="l26", node_source=sw21, node_target=sw23, type=LinkType.DIRECT))
    l27 = dp.addLink(LinkPair(name="l27", node_source=sw24, node_target=sw25, type=LinkType.DIRECT))
    l28 = dp.addLink(LinkPair(name="l28", node_source=sw24, node_target=sw26, type=LinkType.DIRECT))
    l29 = dp.addLink(LinkPair(name="l29", node_source=sw27, node_target=sw28, type=LinkType.DIRECT))
    l30 = dp.addLink(LinkPair(name="l30", node_source=sw27, node_target=sw31, type=LinkType.DIRECT))
    
    l31 = dp.addLink(LinkPair(name="l31", node_source=sw28, node_target=sw29, type=LinkType.DIRECT))
    l32 = dp.addLink(LinkPair(name="l32", node_source=sw28, node_target=sw30, type=LinkType.DIRECT))
    l33 = dp.addLink(LinkPair(name="l33", node_source=sw31, node_target=sw32, type=LinkType.DIRECT))
    l34 = dp.addLink(LinkPair(name="l34", node_source=sw31, node_target=sw33, type=LinkType.DIRECT))
    l35 = dp.addLink(LinkPair(name="l35", node_source=sw34, node_target=sw35, type=LinkType.DIRECT))
    l36 = dp.addLink(LinkPair(name="l36", node_source=sw34, node_target=sw50, type=LinkType.DIRECT))
    l37 = dp.addLink(LinkPair(name="l37", node_source=sw35, node_target=sw36, type=LinkType.DIRECT))
    l38 = dp.addLink(LinkPair(name="l38", node_source=sw35, node_target=sw43, type=LinkType.DIRECT))
    l39 = dp.addLink(LinkPair(name="l39", node_source=sw36, node_target=sw37, type=LinkType.DIRECT))
    l40 = dp.addLink(LinkPair(name="l40", node_source=sw36, node_target=sw40, type=LinkType.DIRECT))
    l41 = dp.addLink(LinkPair(name="l41", node_source=sw37, node_target=sw38, type=LinkType.DIRECT))
    l42 = dp.addLink(LinkPair(name="l42", node_source=sw37, node_target=sw39, type=LinkType.DIRECT))
    l43 = dp.addLink(LinkPair(name="l43", node_source=sw40, node_target=sw41, type=LinkType.DIRECT))
    l44 = dp.addLink(LinkPair(name="l44", node_source=sw40, node_target=sw42, type=LinkType.DIRECT))
    l45 = dp.addLink(LinkPair(name="l45", node_source=sw43, node_target=sw44, type=LinkType.DIRECT))
    l46 = dp.addLink(LinkPair(name="l46", node_source=sw43, node_target=sw47, type=LinkType.DIRECT))
    l47 = dp.addLink(LinkPair(name="l47", node_source=sw44, node_target=sw45, type=LinkType.DIRECT))
    l48 = dp.addLink(LinkPair(name="l48", node_source=sw44, node_target=sw46, type=LinkType.DIRECT))
    l49 = dp.addLink(LinkPair(name="l49", node_source=sw47, node_target=sw48, type=LinkType.DIRECT))
    l50 = dp.addLink(LinkPair(name="l50", node_source=sw47, node_target=sw49, type=LinkType.DIRECT))
    l51 = dp.addLink(LinkPair(name="l51", node_source=sw50, node_target=sw51, type=LinkType.DIRECT))
    l52 = dp.addLink(LinkPair(name="l52", node_source=sw50, node_target=sw58, type=LinkType.DIRECT))
    l53 = dp.addLink(LinkPair(name="l53", node_source=sw51, node_target=sw52, type=LinkType.DIRECT))
    l54 = dp.addLink(LinkPair(name="l54", node_source=sw51, node_target=sw55, type=LinkType.DIRECT))
    l55 = dp.addLink(LinkPair(name="l55", node_source=sw52, node_target=sw53, type=LinkType.DIRECT))
    l56 = dp.addLink(LinkPair(name="l56", node_source=sw52, node_target=sw54, type=LinkType.DIRECT))
    l57 = dp.addLink(LinkPair(name="l57", node_source=sw55, node_target=sw56, type=LinkType.DIRECT))
    l58 = dp.addLink(LinkPair(name="l58", node_source=sw55, node_target=sw67, type=LinkType.DIRECT))
    l59 = dp.addLink(LinkPair(name="l59", node_source=sw58, node_target=sw59, type=LinkType.DIRECT))
    l60 = dp.addLink(LinkPair(name="l60", node_source=sw58, node_target=sw62, type=LinkType.DIRECT))
    l61 = dp.addLink(LinkPair(name="l61", node_source=sw59, node_target=sw60, type=LinkType.DIRECT))
    l62 = dp.addLink(LinkPair(name="l62", node_source=sw59, node_target=sw61, type=LinkType.DIRECT))

    l63 = dp.addLink(LinkPair(name="l63", node_source=sw62, node_target=sw63, type=LinkType.DIRECT))
    l64 = dp.addLink(LinkPair(name="l64", node_source=sw62, node_target=sw64, type=LinkType.DIRECT))
    l65 = dp.addLink(LinkPair(name="l65", node_source=sw65, node_target=sw66, type=LinkType.DIRECT))
    l66 = dp.addLink(LinkPair(name="l66", node_source=sw65, node_target=sw97, type=LinkType.DIRECT))
    l67 = dp.addLink(LinkPair(name="l67", node_source=sw66, node_target=sw67, type=LinkType.DIRECT))
    l68 = dp.addLink(LinkPair(name="l68", node_source=sw66, node_target=sw82, type=LinkType.DIRECT))
    l69 = dp.addLink(LinkPair(name="l69", node_source=sw67, node_target=sw68, type=LinkType.DIRECT))
    l70 = dp.addLink(LinkPair(name="l70", node_source=sw67, node_target=sw75, type=LinkType.DIRECT))
    l71 = dp.addLink(LinkPair(name="l71", node_source=sw68, node_target=sw69, type=LinkType.DIRECT))
    l72 = dp.addLink(LinkPair(name="l72", node_source=sw68, node_target=sw72, type=LinkType.DIRECT))
    l73 = dp.addLink(LinkPair(name="l73", node_source=sw69, node_target=sw70, type=LinkType.DIRECT))
    l74 = dp.addLink(LinkPair(name="l74", node_source=sw69, node_target=sw71, type=LinkType.DIRECT))
    l75 = dp.addLink(LinkPair(name="l75", node_source=sw72, node_target=sw73, type=LinkType.DIRECT))
    l76 = dp.addLink(LinkPair(name="l76", node_source=sw72, node_target=sw74, type=LinkType.DIRECT))
    l77 = dp.addLink(LinkPair(name="l77", node_source=sw75, node_target=sw76, type=LinkType.DIRECT))
    l78 = dp.addLink(LinkPair(name="l78", node_source=sw75, node_target=sw79, type=LinkType.DIRECT))
    l79 = dp.addLink(LinkPair(name="l79", node_source=sw76, node_target=sw77, type=LinkType.DIRECT))
    l80 = dp.addLink(LinkPair(name="l80", node_source=sw76, node_target=sw78, type=LinkType.DIRECT))
    l81 = dp.addLink(LinkPair(name="l81", node_source=sw79, node_target=sw80, type=LinkType.DIRECT))
    l82 = dp.addLink(LinkPair(name="l82", node_source=sw79, node_target=sw81, type=LinkType.DIRECT))
    l83 = dp.addLink(LinkPair(name="l83", node_source=sw82, node_target=sw83, type=LinkType.DIRECT))
    l84 = dp.addLink(LinkPair(name="l84", node_source=sw82, node_target=sw90, type=LinkType.DIRECT))
    l85 = dp.addLink(LinkPair(name="l85", node_source=sw83, node_target=sw84, type=LinkType.DIRECT))
    l86 = dp.addLink(LinkPair(name="l86", node_source=sw83, node_target=sw87, type=LinkType.DIRECT))
    l87 = dp.addLink(LinkPair(name="l87", node_source=sw84, node_target=sw85, type=LinkType.DIRECT))
    l88 = dp.addLink(LinkPair(name="l88", node_source=sw84, node_target=sw86, type=LinkType.DIRECT))
    l89 = dp.addLink(LinkPair(name="l89", node_source=sw87, node_target=sw88, type=LinkType.DIRECT))
    l90 = dp.addLink(LinkPair(name="l90", node_source=sw87, node_target=sw89, type=LinkType.DIRECT))
    l91 = dp.addLink(LinkPair(name="l91", node_source=sw90, node_target=sw91, type=LinkType.DIRECT))
    l92 = dp.addLink(LinkPair(name="l92", node_source=sw90, node_target=sw94, type=LinkType.DIRECT))
    l93 = dp.addLink(LinkPair(name="l93", node_source=sw91, node_target=sw92, type=LinkType.DIRECT))
    l94 = dp.addLink(LinkPair(name="l94", node_source=sw91, node_target=sw93, type=LinkType.DIRECT))
    l95 = dp.addLink(LinkPair(name="l95", node_source=sw94, node_target=sw95, type=LinkType.DIRECT))
    l96 = dp.addLink(LinkPair(name="l96", node_source=sw94, node_target=sw96, type=LinkType.DIRECT))
    l97 = dp.addLink(LinkPair(name="l97", node_source=sw97, node_target=sw98, type=LinkType.DIRECT))
    l98 = dp.addLink(LinkPair(name="l98", node_source=sw97, node_target=sw113, type=LinkType.DIRECT))
    l99 = dp.addLink(LinkPair(name="l99", node_source=sw98, node_target=sw99, type=LinkType.DIRECT))
    l100 = dp.addLink(LinkPair(name="l100", node_source=sw98, node_target=sw106, type=LinkType.DIRECT))
    l101 = dp.addLink(LinkPair(name="l101", node_source=sw99, node_target=sw100, type=LinkType.DIRECT))
    l102 = dp.addLink(LinkPair(name="l102", node_source=sw99, node_target=sw103, type=LinkType.DIRECT))
    l103 = dp.addLink(LinkPair(name="l103", node_source=sw100, node_target=sw101, type=LinkType.DIRECT))
    l104 = dp.addLink(LinkPair(name="l104", node_source=sw100, node_target=sw102, type=LinkType.DIRECT))
    l105 = dp.addLink(LinkPair(name="l105", node_source=sw103, node_target=sw104, type=LinkType.DIRECT))
    l106 = dp.addLink(LinkPair(name="l106", node_source=sw103, node_target=sw105, type=LinkType.DIRECT))
    l107 = dp.addLink(LinkPair(name="l107", node_source=sw106, node_target=sw107, type=LinkType.DIRECT))
    l108 = dp.addLink(LinkPair(name="l108", node_source=sw106, node_target=sw110, type=LinkType.DIRECT))
    l109 = dp.addLink(LinkPair(name="l109", node_source=sw107, node_target=sw108, type=LinkType.DIRECT))
    l110 = dp.addLink(LinkPair(name="l110", node_source=sw107, node_target=sw109, type=LinkType.DIRECT))
    l111 = dp.addLink(LinkPair(name="l111", node_source=sw110, node_target=sw111, type=LinkType.DIRECT))
    l112 = dp.addLink(LinkPair(name="l112", node_source=sw110, node_target=sw112, type=LinkType.DIRECT))
    l113 = dp.addLink(LinkPair(name="l113", node_source=sw113, node_target=sw114, type=LinkType.DIRECT))
    l114 = dp.addLink(LinkPair(name="l114", node_source=sw113, node_target=sw121, type=LinkType.DIRECT))
    l115 = dp.addLink(LinkPair(name="l115", node_source=sw114, node_target=sw115, type=LinkType.DIRECT))
    l116 = dp.addLink(LinkPair(name="l116", node_source=sw114, node_target=sw118, type=LinkType.DIRECT))
    l117 = dp.addLink(LinkPair(name="l117", node_source=sw115, node_target=sw116, type=LinkType.DIRECT))
    l118 = dp.addLink(LinkPair(name="l118", node_source=sw115, node_target=sw117, type=LinkType.DIRECT))
    l119 = dp.addLink(LinkPair(name="l119", node_source=sw118, node_target=sw119, type=LinkType.DIRECT))
    l120 = dp.addLink(LinkPair(name="l120", node_source=sw118, node_target=sw120, type=LinkType.DIRECT))
    l121 = dp.addLink(LinkPair(name="l121", node_source=sw121, node_target=sw122, type=LinkType.DIRECT))
    l122 = dp.addLink(LinkPair(name="l122", node_source=sw121, node_target=sw125, type=LinkType.DIRECT))
    l123 = dp.addLink(LinkPair(name="l123", node_source=sw121, node_target=sw123, type=LinkType.DIRECT))
    l124 = dp.addLink(LinkPair(name="l124", node_source=sw121, node_target=sw124, type=LinkType.DIRECT))
    l125 = dp.addLink(LinkPair(name="l125", node_source=sw125, node_target=sw126, type=LinkType.DIRECT))
    l126 = dp.addLink(LinkPair(name="l126", node_source=sw125, node_target=sw127, type=LinkType.DIRECT))


    hl1 = dp.addLink(LinkPair(name="hl1", node_source=h1, node_target=sw63, type=LinkType.HOST))
    hl2 = dp.addLink(LinkPair(name="hl2", node_source=h2, node_target=sw30, type=LinkType.HOST))

    #conecting switchs with controller

    sw1.setController(target=mgnt, bridge="br_oper0")
    sw2.setController(target=mgnt, bridge="br_oper0")
    sw3.setController(target=mgnt, bridge="br_oper0")
    sw4.setController(target=mgnt, bridge="br_oper0")
    sw5.setController(target=mgnt, bridge="br_oper0")
    sw6.setController(target=mgnt, bridge="br_oper0")
    sw7.setController(target=mgnt, bridge="br_oper0")
    sw8.setController(target=mgnt, bridge="br_oper0")
    sw9.setController(target=mgnt, bridge="br_oper0")
    sw10.setController(target=mgnt, bridge="br_oper0")
    sw11.setController(target=mgnt, bridge="br_oper0")
    sw12.setController(target=mgnt, bridge="br_oper0")
    sw13.setController(target=mgnt, bridge="br_oper0")
    sw14.setController(target=mgnt, bridge="br_oper0")
    sw15.setController(target=mgnt, bridge="br_oper0")
    sw16.setController(target=mgnt, bridge="br_oper0")
    sw17.setController(target=mgnt, bridge="br_oper0")
    sw18.setController(target=mgnt, bridge="br_oper0")
    sw19.setController(target=mgnt, bridge="br_oper0")
    sw20.setController(target=mgnt, bridge="br_oper0")
    sw21.setController(target=mgnt, bridge="br_oper0")
    sw22.setController(target=mgnt, bridge="br_oper0")
    sw23.setController(target=mgnt, bridge="br_oper0")
    sw24.setController(target=mgnt, bridge="br_oper0")
    sw25.setController(target=mgnt, bridge="br_oper0")
    sw26.setController(target=mgnt, bridge="br_oper0")
    sw27.setController(target=mgnt, bridge="br_oper0")
    sw28.setController(target=mgnt, bridge="br_oper0")
    sw29.setController(target=mgnt, bridge="br_oper0")
    sw30.setController(target=mgnt, bridge="br_oper0")
    sw31.setController(target=mgnt, bridge="br_oper0")
    sw32.setController(target=mgnt, bridge="br_oper0")
    sw33.setController(target=mgnt, bridge="br_oper0")
    sw34.setController(target=mgnt, bridge="br_oper0")
    sw35.setController(target=mgnt, bridge="br_oper0")
    sw36.setController(target=mgnt, bridge="br_oper0")
    sw37.setController(target=mgnt, bridge="br_oper0")
    sw38.setController(target=mgnt, bridge="br_oper0")
    sw39.setController(target=mgnt, bridge="br_oper0")
    sw40.setController(target=mgnt, bridge="br_oper0")
    sw41.setController(target=mgnt, bridge="br_oper0")
    sw42.setController(target=mgnt, bridge="br_oper0")
    sw43.setController(target=mgnt, bridge="br_oper0")
    sw44.setController(target=mgnt, bridge="br_oper0")
    sw45.setController(target=mgnt, bridge="br_oper0")
    sw46.setController(target=mgnt, bridge="br_oper0")
    sw47.setController(target=mgnt, bridge="br_oper0")
    sw48.setController(target=mgnt, bridge="br_oper0")
    sw49.setController(target=mgnt, bridge="br_oper0")
    sw50.setController(target=mgnt, bridge="br_oper0")
    sw51.setController(target=mgnt, bridge="br_oper0")
    sw52.setController(target=mgnt, bridge="br_oper0")
    sw53.setController(target=mgnt, bridge="br_oper0")
    sw54.setController(target=mgnt, bridge="br_oper0")
    sw55.setController(target=mgnt, bridge="br_oper0")
    sw56.setController(target=mgnt, bridge="br_oper0")
    sw57.setController(target=mgnt, bridge="br_oper0")
    sw58.setController(target=mgnt, bridge="br_oper0")
    sw59.setController(target=mgnt, bridge="br_oper0")
    sw60.setController(target=mgnt, bridge="br_oper0")
    sw61.setController(target=mgnt, bridge="br_oper0")
    sw62.setController(target=mgnt, bridge="br_oper0")
    sw63.setController(target=mgnt, bridge="br_oper0")
    sw64.setController(target=mgnt, bridge="br_oper0")
    sw65.setController(target=mgnt, bridge="br_oper0")
    sw66.setController(target=mgnt, bridge="br_oper0")
    sw67.setController(target=mgnt, bridge="br_oper0")
    sw68.setController(target=mgnt, bridge="br_oper0")
    sw69.setController(target=mgnt, bridge="br_oper0")
    sw70.setController(target=mgnt, bridge="br_oper0")
    sw71.setController(target=mgnt, bridge="br_oper0")
    sw72.setController(target=mgnt, bridge="br_oper0")
    sw73.setController(target=mgnt, bridge="br_oper0")
    sw74.setController(target=mgnt, bridge="br_oper0")
    sw75.setController(target=mgnt, bridge="br_oper0")
    sw76.setController(target=mgnt, bridge="br_oper0")
    sw77.setController(target=mgnt, bridge="br_oper0")
    sw78.setController(target=mgnt, bridge="br_oper0")
    sw79.setController(target=mgnt, bridge="br_oper0")
    sw80.setController(target=mgnt, bridge="br_oper0")
    sw81.setController(target=mgnt, bridge="br_oper0")
    sw82.setController(target=mgnt, bridge="br_oper0")
    sw83.setController(target=mgnt, bridge="br_oper0")
    sw84.setController(target=mgnt, bridge="br_oper0")
    sw85.setController(target=mgnt, bridge="br_oper0")
    sw86.setController(target=mgnt, bridge="br_oper0")
    sw87.setController(target=mgnt, bridge="br_oper0")
    sw88.setController(target=mgnt, bridge="br_oper0")
    sw89.setController(target=mgnt, bridge="br_oper0")
    sw90.setController(target=mgnt, bridge="br_oper0")
    sw91.setController(target=mgnt, bridge="br_oper0")
    sw92.setController(target=mgnt, bridge="br_oper0")
    sw93.setController(target=mgnt, bridge="br_oper0")
    sw94.setController(target=mgnt, bridge="br_oper0")
    sw95.setController(target=mgnt, bridge="br_oper0")
    sw96.setController(target=mgnt, bridge="br_oper0")
    sw97.setController(target=mgnt, bridge="br_oper0")
    sw98.setController(target=mgnt, bridge="br_oper0")
    sw99.setController(target=mgnt, bridge="br_oper0")
    sw100.setController(target=mgnt, bridge="br_oper0")
    sw101.setController(target=mgnt, bridge="br_oper0")
    sw102.setController(target=mgnt, bridge="br_oper0")
    sw103.setController(target=mgnt, bridge="br_oper0")
    sw104.setController(target=mgnt, bridge="br_oper0")
    sw105.setController(target=mgnt, bridge="br_oper0")
    sw106.setController(target=mgnt, bridge="br_oper0")
    sw107.setController(target=mgnt, bridge="br_oper0")
    sw108.setController(target=mgnt, bridge="br_oper0")
    sw109.setController(target=mgnt, bridge="br_oper0")
    sw110.setController(target=mgnt, bridge="br_oper0")
    sw111.setController(target=mgnt, bridge="br_oper0")
    sw112.setController(target=mgnt, bridge="br_oper0")
    sw113.setController(target=mgnt, bridge="br_oper0")
    sw114.setController(target=mgnt, bridge="br_oper0")
    sw115.setController(target=mgnt, bridge="br_oper0")
    sw116.setController(target=mgnt, bridge="br_oper0")
    sw117.setController(target=mgnt, bridge="br_oper0")
    sw118.setController(target=mgnt, bridge="br_oper0")
    sw119.setController(target=mgnt, bridge="br_oper0")
    sw120.setController(target=mgnt, bridge="br_oper0")
    sw121.setController(target=mgnt, bridge="br_oper0")
    sw122.setController(target=mgnt, bridge="br_oper0")
    sw123.setController(target=mgnt, bridge="br_oper0")
    sw124.setController(target=mgnt, bridge="br_oper0")
    sw125.setController(target=mgnt, bridge="br_oper0")
    sw126.setController(target=mgnt, bridge="br_oper0")
    sw127.setController(target=mgnt, bridge="br_oper0")

    cli = Cli(dp)
    cli.cmdloop()
